#!/usr/bin/env bash
# Whisper relay — VPS deploy script (Ubuntu 24.04, systemd + nginx).
#
# Idempotent: safe to re-run; every step tolerates an already-provisioned
# state. Installs nginx + certbot, builds the relay release binary, installs
# the hardened systemd unit with a root-only env file, provisions the
# direct-TLS nginx site and issues the Let's Encrypt certificate.
#
# Usage:
#   WHISPER_DOMAIN=whisper-test.homelab.cfd \
#   WHISPER_CERTBOT_EMAIL=you@example.com \
#   sudo bash server/deploy/deploy.sh
#
# The domain must already point at this host (DNS-only A/AAAA record, no
# Cloudflare proxy) — the client pins the ORIGIN certificate, so proxying
# would break the §9 pinning model.
set -euo pipefail

DOMAIN="${WHISPER_DOMAIN:-whisper-test.homelab.cfd}"
CERTBOT_EMAIL="${WHISPER_CERTBOT_EMAIL:-}"
RELAY_ADDR="127.0.0.1:18080"
REPO_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
APP_DIR="/opt/whisper"
DATA_DIR="${APP_DIR}/data"
ENV_DIR="/etc/whisper"
ENV_FILE="${ENV_DIR}/relay.env"
NGINX_SITE="/etc/nginx/sites-available/whisper-relay"
NGINX_LINK="/etc/nginx/sites-enabled/whisper-relay"

log() { echo "==> $*"; }

log "[1/7] System packages (nginx, certbot)"
apt-get update -y
apt-get install -y nginx certbot python3-certbot-nginx

log "[2/7] Build the relay release binary"
# NOTE: pull the latest code BEFORE running this script (the repo is private
# and the checkout may need credentials):  git -C "${REPO_DIR}" pull --ff-only
cd "${REPO_DIR}"
cargo build --release -p whisper-relay

log "[3/7] Dedicated system user + binary install"
id -u whisper &>/dev/null || useradd --system --home "${APP_DIR}" --shell /usr/sbin/nologin whisper
install -d -o whisper -g whisper "${APP_DIR}" "${DATA_DIR}"
install -o whisper -g whisper "${REPO_DIR}/target/release/whisper-relay" "${APP_DIR}/whisper-relay"
install -o root -g root -m 644 "${REPO_DIR}/server/deploy/whisper-relay.service" /etc/systemd/system/whisper-relay.service

log "[4/7] Root-only env file (/etc/whisper/relay.env)"
install -d -o root -g root -m 700 "${ENV_DIR}"
umask 077
cat > "${ENV_FILE}" <<EOF
# Whisper relay environment — generated by server/deploy/deploy.sh
WHISPER_ADDR=${RELAY_ADDR}
WHISPER_DB_PATH=${DATA_DIR}/relay.db
# nginx is the only peer: rate limiting reads X-Forwarded-For from 127.0.0.1.
WHISPER_TRUSTED_PROXIES=127.0.0.1
WHISPER_METRICS=1
RUST_LOG=info
EOF
chown root:root "${ENV_FILE}"
chmod 600 "${ENV_FILE}"

log "[5/7] systemd unit"
systemctl daemon-reload
systemctl enable --now whisper-relay
systemctl restart whisper-relay
systemctl --no-pager status whisper-relay --lines=0 || true

log "[6/7] nginx site (direct TLS, WSS, overwrites X-Forwarded-For)"
cat > "${NGINX_SITE}" <<EOF
server {
    listen 80;
    listen [::]:80;
    server_name ${DOMAIN};

    # Avatars/media can be a few MiB; the default 1 MiB would reject them.
    client_max_body_size 20m;

    # Envelope + media uploads.
    location /media/ {
        proxy_pass http://127.0.0.1:18080;
        proxy_set_header Host \$host;
        proxy_set_header X-Forwarded-For \$remote_addr;
        proxy_set_header X-Forwarded-Proto https;
    }

    # WebSocket endpoint — the heart of the relay. Upgrade headers are
    # mandatory, and the proxy must not time out an idle chat connection.
    location /ws {
        proxy_pass http://127.0.0.1:18080;
        proxy_http_version 1.1;
        proxy_set_header Upgrade \$http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_set_header Host \$host;
        proxy_set_header X-Forwarded-For \$remote_addr;
        proxy_set_header X-Forwarded-Proto https;
        proxy_read_timeout 3600s;
        proxy_send_timeout 3600s;
    }

    # Liveness probe + optional metrics (WHISPER_METRICS=1).
    location = /healthz {
        proxy_pass http://127.0.0.1:18080;
        proxy_set_header Host \$host;
        proxy_set_header X-Forwarded-For \$remote_addr;
        proxy_set_header X-Forwarded-Proto https;
    }
    location = /metrics {
        proxy_pass http://127.0.0.1:18080;
        proxy_set_header Host \$host;
        proxy_set_header X-Forwarded-For \$remote_addr;
        proxy_set_header X-Forwarded-Proto https;
    }
}
EOF
ln -sfn "${NGINX_SITE}" "${NGINX_LINK}"
nginx -t

log "[7/7] Let's Encrypt certificate (direct TLS)"
if [[ -n "${CERTBOT_EMAIL}" ]]; then
    certbot --nginx -d "${DOMAIN}" --non-interactive --agree-tos -m "${CERTBOT_EMAIL}" --redirect
else
    certbot --nginx -d "${DOMAIN}" --non-interactive --agree-tos --register-unsafely-without-email --redirect
fi
systemctl reload nginx

log "Deploy complete."
log "  relay:   wss://${DOMAIN}/ws  (systemd: whisper-relay)"
log "  health:  https://${DOMAIN}/healthz"
log "  metrics: https://${DOMAIN}/metrics (WHISPER_METRICS=1)"
log "  DB:      ${DATA_DIR}/relay.db (whisper user, TTL 7d)"
log
log "Two-machine E2EE test: set the relay URL to wss://${DOMAIN}/ws"
log "in the desktop client, or run with WHISPER_RELAY_URL=wss://${DOMAIN}/ws."
