// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `authenticated_metadata`, `decrypt_package`, `derive_key_with_costs`, `derive_key`, `encrypt_package`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `BackupError`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `assert_fields_are_eq`, `eq`, `fmt`, `fmt`

/// Seal `plaintext` (the full backup body as JSON) under `password`.
/// Returns the v2 package as a JSON string. A fresh salt + nonce per call.
/// FFI-facing: errors are human-readable strings.
Future<String> backupEncrypt({
  required String plaintext,
  required String password,
}) => RustLib.instance.api.crateApiBackupBackupEncrypt(
  plaintext: plaintext,
  password: password,
);

/// Open a v2 package (JSON string) produced by [`backup_encrypt`].
/// FFI-facing: errors are human-readable strings.
Future<String> backupDecrypt({
  required String packageJson,
  required String password,
}) => RustLib.instance.api.crateApiBackupBackupDecrypt(
  packageJson: packageJson,
  password: password,
);
