// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `handle_inbound`, `handle_server_message`, `push_event`, `send_payload`, `send_wire`, `send`, `sha2_placeholder`, `start_chat`, `xor_with_key`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `ClientInner`, `ClientMessage`, `FriendRequestIncoming`, `GroupInviteInfo`, `GroupMember`, `RelayEnvelope`, `SearchResult`, `ServerMessage`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `clone`, `clone`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`

Future<IdentityInfo> identityCreate() =>
    RustLib.instance.api.crateApiWhisperIdentityCreate();

Future<IdentityInfo> identityFromJson({required String json}) =>
    RustLib.instance.api.crateApiWhisperIdentityFromJson(json: json);

/// Sign a username binding (`username || 0x00 || curve25519_key`).
Future<String> signUsername({required String json, required String username}) =>
    RustLib.instance.api.crateApiWhisperSignUsername(
      json: json,
      username: username,
    );

/// Build a `whisper://invite` link for our identity.
Future<String> inviteLink({required String json}) =>
    RustLib.instance.api.crateApiWhisperInviteLink(json: json);

Future<bool> isValidPeerId({required String peerId}) =>
    RustLib.instance.api.crateApiWhisperIsValidPeerId(peerId: peerId);

/// Compute the 60-digit safety number for our identity vs `their_curve25519`
/// (base64 X25519 public key from a profile). Returns an error for an
/// invalid key.
Future<String> safetyNumber({
  required String identityJson,
  required String theirCurve25519,
}) => RustLib.instance.api.crateApiWhisperSafetyNumber(
  identityJson: identityJson,
  theirCurve25519: theirCurve25519,
);

/// Short 12-digit safety number fragment for compact surfaces.
Future<String> shortSafetyNumber({
  required String identityJson,
  required String theirCurve25519,
}) => RustLib.instance.api.crateApiWhisperShortSafetyNumber(
  identityJson: identityJson,
  theirCurve25519: theirCurve25519,
);

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<WhisperClient>>
abstract class WhisperClient implements RustOpaqueInterface {
  Future<void> acceptFriendRequest({required String peer});

  Future<void> acceptGroupInvite({required String groupId});

  Future<void> addGroupMember({
    required String groupId,
    required String peerId,
  });

  Future<void> connect({String? relayUrl, required String identityJson});

  Future<void> createGroup({required String name});

  Future<void> declineFriendRequest({required String peer});

  Future<void> declineGroupInvite({required String groupId});

  static Future<WhisperClient> default_() =>
      RustLib.instance.api.crateApiWhisperWhisperClientDefault();

  /// Delete a message for everyone.
  Future<void> deleteMessage({
    required String peerId,
    required String messageId,
  });

  Future<void> demoteMember({required String groupId, required String peerId});

  /// Edit a message's text.
  Future<void> editMessage({
    required String peerId,
    required String messageId,
    required String text,
  });

  Future<void> getGroupInfo({required String groupId});

  Future<void> getGroupJoinLink({required String groupId});

  Future<void> getPresence({required String peerId});

  /// Fetch a peer's public profile.
  Future<void> getProfile({required String peerId});

  Future<void> inviteToGroup({required String groupId, required String peerId});

  Future<bool> isConnected();

  Future<void> joinGroup({required String groupId, required String token});

  Future<void> leaveGroup({required String groupId});

  // HINT: Make it `#[frb(sync)]` to let it become the default constructor of Dart class.
  static Future<WhisperClient> newInstance() =>
      RustLib.instance.api.crateApiWhisperWhisperClientNew();

  Future<void> promoteMember({required String groupId, required String peerId});

  Future<void> refreshContacts();

  Future<void> refreshFriendRequests();

  Future<void> refreshGroupInvites();

  /// Register (or refresh) a signed username + optional display name.
  Future<void> registerProfile({
    required String username,
    required String signature,
    String? displayName,
  });

  Future<void> removeContact({required String peer});

  Future<void> removeMember({required String groupId, required String peerId});

  Future<void> renameGroup({required String groupId, required String name});

  /// Search the public directory by username / peer ID.
  Future<void> searchUsers({required String query});

  Future<void> sendFriendRequest({required String target});

  /// Send a text message to a group (Megolm-encrypted). The session key is
  /// shared to members over 1:1 E2EE; for the MVP we reuse the same
  /// envelope routing with a group recipient and an encrypted payload.
  Future<void> sendGroupMessage({
    required String groupId,
    required String text,
  });

  Future<void> sendMessage({required String peerId, required String text});

  Future<void> sendMessageFull({
    required String peerId,
    required String text,
    String? quote,
    String? messageId,
    BigInt? expiresInSeconds,
  });

  /// Send an emoji reaction to a message (encrypted inside the session).
  Future<void> sendReaction({
    required String peerId,
    required String messageId,
    required String emoji,
  });

  /// Send a read receipt for `message_id` (encrypted inside the session).
  Future<void> sendReadReceipt({
    required String peerId,
    required String messageId,
  });

  /// Upload (or replace) our avatar: base64 image blob (= 2 MiB), reuses
  /// the signed profile registration so the username binding stays valid.
  Future<void> setAvatar({
    required String username,
    required String signature,
    required String avatarB64,
  });

  /// Set our public display name.
  Future<void> setDisplayName({required String displayName});

  /// Toggle whether our online status is visible to others.
  Future<void> setPrivacy({required bool presenceVisible});

  Future<List<ChatEvent>> takeEvents();

  Future<void> watchPresence({required String peerId});
}

/// One event emitted by the relay loop, drained by the UI via `take_events`.
/// `kind` is one of: connected, disconnected, message, message_sent, error,
/// contacts, friend_requests, friend_request_received, presence, profile,
/// search_results, group_created, group_info, group_member_added,
/// group_member_left, group_invite_received, group_invites, group_join_ok,
/// group_renamed, session_established.
class ChatEvent {
  final String kind;
  final String peerId;
  final String? text;
  final String? error;

  const ChatEvent({
    required this.kind,
    required this.peerId,
    this.text,
    this.error,
  });

  @override
  int get hashCode =>
      kind.hashCode ^ peerId.hashCode ^ text.hashCode ^ error.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ChatEvent &&
          runtimeType == other.runtimeType &&
          kind == other.kind &&
          peerId == other.peerId &&
          text == other.text &&
          error == other.error;
}

class IdentityInfo {
  final String peerId;
  final String json;

  const IdentityInfo({required this.peerId, required this.json});

  @override
  int get hashCode => peerId.hashCode ^ json.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is IdentityInfo &&
          runtimeType == other.runtimeType &&
          peerId == other.peerId &&
          json == other.json;
}
