// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `handle_inbound`, `handle_server_message`, `push_event`, `send_wire`, `send`, `start_chat`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `ClientInner`, `ClientMessage`, `RelayEnvelope`, `ServerMessage`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `clone`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`

Future<IdentityInfo> identityCreate() =>
    RustLib.instance.api.crateApiWhisperIdentityCreate();

Future<IdentityInfo> identityFromJson({required String json}) =>
    RustLib.instance.api.crateApiWhisperIdentityFromJson(json: json);

/// Validate a peer ID shape (24 lowercase hex chars).
Future<bool> isValidPeerId({required String peerId}) =>
    RustLib.instance.api.crateApiWhisperIsValidPeerId(peerId: peerId);

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<WhisperClient>>
abstract class WhisperClient implements RustOpaqueInterface {
  /// Accept a pending friend request from `peer`.
  Future<void> acceptFriendRequest({required String peer});

  /// Connect to the relay: open the WebSocket, send the signed hello and
  /// publish our pre-key bundle so other peers can start sessions.
  Future<void> connect({String? relayUrl, required String identityJson});

  static Future<WhisperClient> default_() =>
      RustLib.instance.api.crateApiWhisperWhisperClientDefault();

  // HINT: Make it `#[frb(sync)]` to let it become the default constructor of Dart class.
  static Future<WhisperClient> newInstance() =>
      RustLib.instance.api.crateApiWhisperWhisperClientNew();

  /// Ask the relay for our accepted contacts (as peer IDs).
  Future<void> refreshContacts();

  /// Ask the relay for pending friend requests.
  Future<void> refreshFriendRequests();

  /// Send a friend request to `target`.
  Future<void> sendFriendRequest({required String target});

  /// Send a text message to `peer_id`, establishing a Double Ratchet
  /// session with a handshake on the first message.
  Future<void> sendMessage({required String peerId, required String text});

  /// Drain all pending events (polled by the UI, e.g. once per second).
  Future<List<ChatEvent>> takeEvents();
}

/// One event emitted by the relay loop, drained by the UI via `take_events`.
class ChatEvent {
  final String kind;
  final String peerId;
  final String? text;
  final String? error;

  const ChatEvent({
    required this.kind,
    required this.peerId,
    this.text,
    this.error,
  });

  @override
  int get hashCode =>
      kind.hashCode ^ peerId.hashCode ^ text.hashCode ^ error.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ChatEvent &&
          runtimeType == other.runtimeType &&
          kind == other.kind &&
          peerId == other.peerId &&
          text == other.text &&
          error == other.error;
}

/// A freshly created (or loaded) identity: its peer ID plus the JSON blob to
/// persist on the device.
class IdentityInfo {
  final String peerId;
  final String json;

  const IdentityInfo({required this.peerId, required this.json});

  @override
  int get hashCode => peerId.hashCode ^ json.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is IdentityInfo &&
          runtimeType == other.runtimeType &&
          peerId == other.peerId &&
          json == other.json;
}
