// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'api/whisper.dart';

import 'dart:async';
import 'dart:convert';

import 'frb_generated.dart';
import 'frb_generated.io.dart'
    if (dart.library.js_interop) 'frb_generated.web.dart';

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Main entrypoint of the Rust API
class RustLib extends BaseEntrypoint<RustLibApi, RustLibApiImpl, RustLibWire> {
  @internal
  static final instance = RustLib._();

  RustLib._();

  /// Initialize flutter_rust_bridge
  static Future<void> init({
    RustLibApi? api,
    BaseHandler? handler,
    ExternalLibrary? externalLibrary,
    bool forceSameCodegenVersion = true,
  }) async {
    await instance.initImpl(
      api: api,
      handler: handler,
      externalLibrary: externalLibrary,
      forceSameCodegenVersion: forceSameCodegenVersion,
    );
  }

  /// Initialize flutter_rust_bridge in mock mode.
  /// No libraries for FFI are loaded.
  static void initMock({required RustLibApi api}) {
    instance.initMockImpl(api: api);
  }

  /// Dispose flutter_rust_bridge
  ///
  /// The call to this function is optional, since flutter_rust_bridge (and everything else)
  /// is automatically disposed when the app stops.
  static void dispose() => instance.disposeImpl();

  @override
  ApiImplConstructor<RustLibApiImpl, RustLibWire> get apiImplConstructor =>
      RustLibApiImpl.new;

  @override
  WireConstructor<RustLibWire> get wireConstructor =>
      RustLibWire.fromExternalLibrary;

  @override
  Future<void> executeRustInitializers() async {}

  @override
  ExternalLibraryLoaderConfig get defaultExternalLibraryLoaderConfig =>
      kDefaultExternalLibraryLoaderConfig;

  @override
  String get codegenVersion => '2.12.0';

  @override
  int get rustContentHash => 445404312;

  static const kDefaultExternalLibraryLoaderConfig =
      ExternalLibraryLoaderConfig(
        stem: 'whisper_core',
        ioDirectory: 'rust/target/release/',
        webPrefix: 'pkg/',
        wasmBindgenName: 'wasm_bindgen',
      );
}

abstract class RustLibApi extends BaseApi {
  Future<void> crateApiWhisperWhisperClientAcceptFriendRequest({
    required WhisperClient that,
    required String peer,
  });

  Future<void> crateApiWhisperWhisperClientConnect({
    required WhisperClient that,
    String? relayUrl,
    required String identityJson,
  });

  Future<WhisperClient> crateApiWhisperWhisperClientDefault();

  Future<WhisperClient> crateApiWhisperWhisperClientNew();

  Future<void> crateApiWhisperWhisperClientRefreshContacts({
    required WhisperClient that,
  });

  Future<void> crateApiWhisperWhisperClientRefreshFriendRequests({
    required WhisperClient that,
  });

  Future<void> crateApiWhisperWhisperClientSendFriendRequest({
    required WhisperClient that,
    required String target,
  });

  Future<void> crateApiWhisperWhisperClientSendMessage({
    required WhisperClient that,
    required String peerId,
    required String text,
  });

  Future<List<ChatEvent>> crateApiWhisperWhisperClientTakeEvents({
    required WhisperClient that,
  });

  Future<void> crateApiWhisperWhisperClientWatchPresence({
    required WhisperClient that,
    required String peerId,
  });

  Future<IdentityInfo> crateApiWhisperIdentityCreate();

  Future<IdentityInfo> crateApiWhisperIdentityFromJson({required String json});

  Future<bool> crateApiWhisperIsValidPeerId({required String peerId});

  RustArcIncrementStrongCountFnType
  get rust_arc_increment_strong_count_WhisperClient;

  RustArcDecrementStrongCountFnType
  get rust_arc_decrement_strong_count_WhisperClient;

  CrossPlatformFinalizerArg
  get rust_arc_decrement_strong_count_WhisperClientPtr;
}

class RustLibApiImpl extends RustLibApiImplPlatform implements RustLibApi {
  RustLibApiImpl({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @override
  Future<void> crateApiWhisperWhisperClientAcceptFriendRequest({
    required WhisperClient that,
    required String peer,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerWhisperClient(
            that,
            serializer,
          );
          sse_encode_String(peer, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 1,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiWhisperWhisperClientAcceptFriendRequestConstMeta,
        argValues: [that, peer],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiWhisperWhisperClientAcceptFriendRequestConstMeta =>
      const TaskConstMeta(
        debugName: "WhisperClient_accept_friend_request",
        argNames: ["that", "peer"],
      );

  @override
  Future<void> crateApiWhisperWhisperClientConnect({
    required WhisperClient that,
    String? relayUrl,
    required String identityJson,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerWhisperClient(
            that,
            serializer,
          );
          sse_encode_opt_String(relayUrl, serializer);
          sse_encode_String(identityJson, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 2,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiWhisperWhisperClientConnectConstMeta,
        argValues: [that, relayUrl, identityJson],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiWhisperWhisperClientConnectConstMeta =>
      const TaskConstMeta(
        debugName: "WhisperClient_connect",
        argNames: ["that", "relayUrl", "identityJson"],
      );

  @override
  Future<WhisperClient> crateApiWhisperWhisperClientDefault() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 3,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData:
              sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerWhisperClient,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiWhisperWhisperClientDefaultConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiWhisperWhisperClientDefaultConstMeta =>
      const TaskConstMeta(debugName: "WhisperClient_default", argNames: []);

  @override
  Future<WhisperClient> crateApiWhisperWhisperClientNew() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 4,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData:
              sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerWhisperClient,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiWhisperWhisperClientNewConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiWhisperWhisperClientNewConstMeta =>
      const TaskConstMeta(debugName: "WhisperClient_new", argNames: []);

  @override
  Future<void> crateApiWhisperWhisperClientRefreshContacts({
    required WhisperClient that,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerWhisperClient(
            that,
            serializer,
          );
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 5,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiWhisperWhisperClientRefreshContactsConstMeta,
        argValues: [that],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiWhisperWhisperClientRefreshContactsConstMeta =>
      const TaskConstMeta(
        debugName: "WhisperClient_refresh_contacts",
        argNames: ["that"],
      );

  @override
  Future<void> crateApiWhisperWhisperClientRefreshFriendRequests({
    required WhisperClient that,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerWhisperClient(
            that,
            serializer,
          );
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 6,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiWhisperWhisperClientRefreshFriendRequestsConstMeta,
        argValues: [that],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta
  get kCrateApiWhisperWhisperClientRefreshFriendRequestsConstMeta =>
      const TaskConstMeta(
        debugName: "WhisperClient_refresh_friend_requests",
        argNames: ["that"],
      );

  @override
  Future<void> crateApiWhisperWhisperClientSendFriendRequest({
    required WhisperClient that,
    required String target,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerWhisperClient(
            that,
            serializer,
          );
          sse_encode_String(target, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 7,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiWhisperWhisperClientSendFriendRequestConstMeta,
        argValues: [that, target],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiWhisperWhisperClientSendFriendRequestConstMeta =>
      const TaskConstMeta(
        debugName: "WhisperClient_send_friend_request",
        argNames: ["that", "target"],
      );

  @override
  Future<void> crateApiWhisperWhisperClientSendMessage({
    required WhisperClient that,
    required String peerId,
    required String text,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerWhisperClient(
            that,
            serializer,
          );
          sse_encode_String(peerId, serializer);
          sse_encode_String(text, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 8,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiWhisperWhisperClientSendMessageConstMeta,
        argValues: [that, peerId, text],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiWhisperWhisperClientSendMessageConstMeta =>
      const TaskConstMeta(
        debugName: "WhisperClient_send_message",
        argNames: ["that", "peerId", "text"],
      );

  @override
  Future<List<ChatEvent>> crateApiWhisperWhisperClientTakeEvents({
    required WhisperClient that,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerWhisperClient(
            that,
            serializer,
          );
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 9,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_chat_event,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiWhisperWhisperClientTakeEventsConstMeta,
        argValues: [that],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiWhisperWhisperClientTakeEventsConstMeta =>
      const TaskConstMeta(
        debugName: "WhisperClient_take_events",
        argNames: ["that"],
      );

  @override
  Future<void> crateApiWhisperWhisperClientWatchPresence({
    required WhisperClient that,
    required String peerId,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerWhisperClient(
            that,
            serializer,
          );
          sse_encode_String(peerId, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 10,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiWhisperWhisperClientWatchPresenceConstMeta,
        argValues: [that, peerId],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiWhisperWhisperClientWatchPresenceConstMeta =>
      const TaskConstMeta(
        debugName: "WhisperClient_watch_presence",
        argNames: ["that", "peerId"],
      );

  @override
  Future<IdentityInfo> crateApiWhisperIdentityCreate() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 11,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_identity_info,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiWhisperIdentityCreateConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiWhisperIdentityCreateConstMeta =>
      const TaskConstMeta(debugName: "identity_create", argNames: []);

  @override
  Future<IdentityInfo> crateApiWhisperIdentityFromJson({required String json}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(json, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 12,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_identity_info,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiWhisperIdentityFromJsonConstMeta,
        argValues: [json],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiWhisperIdentityFromJsonConstMeta =>
      const TaskConstMeta(debugName: "identity_from_json", argNames: ["json"]);

  @override
  Future<bool> crateApiWhisperIsValidPeerId({required String peerId}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(peerId, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 13,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_bool,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiWhisperIsValidPeerIdConstMeta,
        argValues: [peerId],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiWhisperIsValidPeerIdConstMeta =>
      const TaskConstMeta(debugName: "is_valid_peer_id", argNames: ["peerId"]);

  RustArcIncrementStrongCountFnType
  get rust_arc_increment_strong_count_WhisperClient => wire
      .rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerWhisperClient;

  RustArcDecrementStrongCountFnType
  get rust_arc_decrement_strong_count_WhisperClient => wire
      .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerWhisperClient;

  @protected
  WhisperClient
  dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerWhisperClient(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return WhisperClientImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  WhisperClient
  dco_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerWhisperClient(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return WhisperClientImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  WhisperClient
  dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerWhisperClient(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return WhisperClientImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  String dco_decode_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as String;
  }

  @protected
  bool dco_decode_bool(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as bool;
  }

  @protected
  ChatEvent dco_decode_chat_event(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 4)
      throw Exception('unexpected arr length: expect 4 but see ${arr.length}');
    return ChatEvent(
      kind: dco_decode_String(arr[0]),
      peerId: dco_decode_String(arr[1]),
      text: dco_decode_opt_String(arr[2]),
      error: dco_decode_opt_String(arr[3]),
    );
  }

  @protected
  IdentityInfo dco_decode_identity_info(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2)
      throw Exception('unexpected arr length: expect 2 but see ${arr.length}');
    return IdentityInfo(
      peerId: dco_decode_String(arr[0]),
      json: dco_decode_String(arr[1]),
    );
  }

  @protected
  List<ChatEvent> dco_decode_list_chat_event(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_chat_event).toList();
  }

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as Uint8List;
  }

  @protected
  String? dco_decode_opt_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_String(raw);
  }

  @protected
  int dco_decode_u_8(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  void dco_decode_unit(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return;
  }

  @protected
  BigInt dco_decode_usize(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeU64(raw);
  }

  @protected
  WhisperClient
  sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerWhisperClient(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return WhisperClientImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  WhisperClient
  sse_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerWhisperClient(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return WhisperClientImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  WhisperClient
  sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerWhisperClient(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return WhisperClientImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  String sse_decode_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_list_prim_u_8_strict(deserializer);
    return utf8.decoder.convert(inner);
  }

  @protected
  bool sse_decode_bool(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8() != 0;
  }

  @protected
  ChatEvent sse_decode_chat_event(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_kind = sse_decode_String(deserializer);
    var var_peerId = sse_decode_String(deserializer);
    var var_text = sse_decode_opt_String(deserializer);
    var var_error = sse_decode_opt_String(deserializer);
    return ChatEvent(
      kind: var_kind,
      peerId: var_peerId,
      text: var_text,
      error: var_error,
    );
  }

  @protected
  IdentityInfo sse_decode_identity_info(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_peerId = sse_decode_String(deserializer);
    var var_json = sse_decode_String(deserializer);
    return IdentityInfo(peerId: var_peerId, json: var_json);
  }

  @protected
  List<ChatEvent> sse_decode_list_chat_event(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <ChatEvent>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_chat_event(deserializer));
    }
    return ans_;
  }

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint8List(len_);
  }

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_String(deserializer));
    } else {
      return null;
    }
  }

  @protected
  int sse_decode_u_8(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8();
  }

  @protected
  void sse_decode_unit(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  BigInt sse_decode_usize(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getBigUint64();
  }

  @protected
  int sse_decode_i_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getInt32();
  }

  @protected
  void
  sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerWhisperClient(
    WhisperClient self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as WhisperClientImpl).frbInternalSseEncode(move: true),
      serializer,
    );
  }

  @protected
  void
  sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerWhisperClient(
    WhisperClient self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as WhisperClientImpl).frbInternalSseEncode(move: false),
      serializer,
    );
  }

  @protected
  void
  sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerWhisperClient(
    WhisperClient self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as WhisperClientImpl).frbInternalSseEncode(move: null),
      serializer,
    );
  }

  @protected
  void sse_encode_String(String self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_prim_u_8_strict(utf8.encoder.convert(self), serializer);
  }

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self ? 1 : 0);
  }

  @protected
  void sse_encode_chat_event(ChatEvent self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.kind, serializer);
    sse_encode_String(self.peerId, serializer);
    sse_encode_opt_String(self.text, serializer);
    sse_encode_opt_String(self.error, serializer);
  }

  @protected
  void sse_encode_identity_info(IdentityInfo self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.peerId, serializer);
    sse_encode_String(self.json, serializer);
  }

  @protected
  void sse_encode_list_chat_event(
    List<ChatEvent> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_chat_event(item, serializer);
    }
  }

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint8List(self);
  }

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_String(self, serializer);
    }
  }

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self);
  }

  @protected
  void sse_encode_unit(void self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  void sse_encode_usize(BigInt self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putBigUint64(self);
  }

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putInt32(self);
  }
}

@sealed
class WhisperClientImpl extends RustOpaque implements WhisperClient {
  // Not to be used by end users
  WhisperClientImpl.frbInternalDcoDecode(List<dynamic> wire)
    : super.frbInternalDcoDecode(wire, _kStaticData);

  // Not to be used by end users
  WhisperClientImpl.frbInternalSseDecode(BigInt ptr, int externalSizeOnNative)
    : super.frbInternalSseDecode(ptr, externalSizeOnNative, _kStaticData);

  static final _kStaticData = RustArcStaticData(
    rustArcIncrementStrongCount:
        RustLib.instance.api.rust_arc_increment_strong_count_WhisperClient,
    rustArcDecrementStrongCount:
        RustLib.instance.api.rust_arc_decrement_strong_count_WhisperClient,
    rustArcDecrementStrongCountPtr:
        RustLib.instance.api.rust_arc_decrement_strong_count_WhisperClientPtr,
  );

  /// Accept a pending friend request from `peer`.
  Future<void> acceptFriendRequest({required String peer}) => RustLib
      .instance
      .api
      .crateApiWhisperWhisperClientAcceptFriendRequest(that: this, peer: peer);

  /// Connect to the relay: open the WebSocket, send the signed hello and
  /// publish our pre-key bundle so other peers can start sessions.
  Future<void> connect({String? relayUrl, required String identityJson}) =>
      RustLib.instance.api.crateApiWhisperWhisperClientConnect(
        that: this,
        relayUrl: relayUrl,
        identityJson: identityJson,
      );

  /// Ask the relay for our accepted contacts (as peer IDs).
  Future<void> refreshContacts() => RustLib.instance.api
      .crateApiWhisperWhisperClientRefreshContacts(that: this);

  /// Ask the relay for pending friend requests.
  Future<void> refreshFriendRequests() => RustLib.instance.api
      .crateApiWhisperWhisperClientRefreshFriendRequests(that: this);

  /// Send a friend request to `target`.
  Future<void> sendFriendRequest({required String target}) =>
      RustLib.instance.api.crateApiWhisperWhisperClientSendFriendRequest(
        that: this,
        target: target,
      );

  /// Send a text message to `peer_id`, establishing a Double Ratchet
  /// session with a handshake on the first message.
  Future<void> sendMessage({required String peerId, required String text}) =>
      RustLib.instance.api.crateApiWhisperWhisperClientSendMessage(
        that: this,
        peerId: peerId,
        text: text,
      );

  /// Drain all pending events (polled by the UI, e.g. once per second).
  Future<List<ChatEvent>> takeEvents() =>
      RustLib.instance.api.crateApiWhisperWhisperClientTakeEvents(that: this);

  /// Subscribe to online/offline pushes for `peer_id`.
  Future<void> watchPresence({required String peerId}) => RustLib.instance.api
      .crateApiWhisperWhisperClientWatchPresence(that: this, peerId: peerId);
}
