// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'api/whisper.dart';

import 'dart:async';
import 'dart:convert';

import 'frb_generated.dart';
import 'frb_generated.io.dart'
    if (dart.library.js_interop) 'frb_generated.web.dart';

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Main entrypoint of the Rust API
class RustLib extends BaseEntrypoint<RustLibApi, RustLibApiImpl, RustLibWire> {
  @internal
  static final instance = RustLib._();

  RustLib._();

  /// Initialize flutter_rust_bridge
  static Future<void> init({
    RustLibApi? api,
    BaseHandler? handler,
    ExternalLibrary? externalLibrary,
    bool forceSameCodegenVersion = true,
  }) async {
    await instance.initImpl(
      api: api,
      handler: handler,
      externalLibrary: externalLibrary,
      forceSameCodegenVersion: forceSameCodegenVersion,
    );
  }

  /// Initialize flutter_rust_bridge in mock mode.
  /// No libraries for FFI are loaded.
  static void initMock({required RustLibApi api}) {
    instance.initMockImpl(api: api);
  }

  /// Dispose flutter_rust_bridge
  ///
  /// The call to this function is optional, since flutter_rust_bridge (and everything else)
  /// is automatically disposed when the app stops.
  static void dispose() => instance.disposeImpl();

  @override
  ApiImplConstructor<RustLibApiImpl, RustLibWire> get apiImplConstructor =>
      RustLibApiImpl.new;

  @override
  WireConstructor<RustLibWire> get wireConstructor =>
      RustLibWire.fromExternalLibrary;

  @override
  Future<void> executeRustInitializers() async {}

  @override
  ExternalLibraryLoaderConfig get defaultExternalLibraryLoaderConfig =>
      kDefaultExternalLibraryLoaderConfig;

  @override
  String get codegenVersion => '2.12.0';

  @override
  int get rustContentHash => 25553631;

  static const kDefaultExternalLibraryLoaderConfig =
      ExternalLibraryLoaderConfig(
        stem: 'whisper_core',
        ioDirectory: 'rust/target/release/',
        webPrefix: 'pkg/',
        wasmBindgenName: 'wasm_bindgen',
      );
}

abstract class RustLibApi extends BaseApi {
  Future<void> crateApiWhisperWhisperClientAcceptFriendRequest({
    required WhisperClient that,
    required String peer,
  });

  Future<void> crateApiWhisperWhisperClientAcceptGroupInvite({
    required WhisperClient that,
    required String groupId,
  });

  Future<void> crateApiWhisperWhisperClientAddGroupMember({
    required WhisperClient that,
    required String groupId,
    required String peerId,
  });

  Future<void> crateApiWhisperWhisperClientConnect({
    required WhisperClient that,
    String? relayUrl,
    required String identityJson,
  });

  Future<void> crateApiWhisperWhisperClientCreateGroup({
    required WhisperClient that,
    required String name,
  });

  Future<void> crateApiWhisperWhisperClientDeclineFriendRequest({
    required WhisperClient that,
    required String peer,
  });

  Future<void> crateApiWhisperWhisperClientDeclineGroupInvite({
    required WhisperClient that,
    required String groupId,
  });

  Future<WhisperClient> crateApiWhisperWhisperClientDefault();

  Future<void> crateApiWhisperWhisperClientDeleteMessage({
    required WhisperClient that,
    required String peerId,
    required String messageId,
  });

  Future<void> crateApiWhisperWhisperClientDemoteMember({
    required WhisperClient that,
    required String groupId,
    required String peerId,
  });

  Future<void> crateApiWhisperWhisperClientEditMessage({
    required WhisperClient that,
    required String peerId,
    required String messageId,
    required String text,
  });

  Future<void> crateApiWhisperWhisperClientGetGroupInfo({
    required WhisperClient that,
    required String groupId,
  });

  Future<void> crateApiWhisperWhisperClientGetGroupJoinLink({
    required WhisperClient that,
    required String groupId,
  });

  Future<void> crateApiWhisperWhisperClientGetPresence({
    required WhisperClient that,
    required String peerId,
  });

  Future<void> crateApiWhisperWhisperClientGetProfile({
    required WhisperClient that,
    required String peerId,
  });

  Future<void> crateApiWhisperWhisperClientInviteToGroup({
    required WhisperClient that,
    required String groupId,
    required String peerId,
  });

  Future<bool> crateApiWhisperWhisperClientIsConnected({
    required WhisperClient that,
  });

  Future<void> crateApiWhisperWhisperClientJoinGroup({
    required WhisperClient that,
    required String groupId,
    required String token,
  });

  Future<void> crateApiWhisperWhisperClientLeaveGroup({
    required WhisperClient that,
    required String groupId,
  });

  Future<WhisperClient> crateApiWhisperWhisperClientNew();

  Future<void> crateApiWhisperWhisperClientPromoteMember({
    required WhisperClient that,
    required String groupId,
    required String peerId,
  });

  Future<void> crateApiWhisperWhisperClientRefreshContacts({
    required WhisperClient that,
  });

  Future<void> crateApiWhisperWhisperClientRefreshFriendRequests({
    required WhisperClient that,
  });

  Future<void> crateApiWhisperWhisperClientRefreshGroupInvites({
    required WhisperClient that,
  });

  Future<void> crateApiWhisperWhisperClientRegisterProfile({
    required WhisperClient that,
    required String username,
    required String signature,
    String? displayName,
  });

  Future<void> crateApiWhisperWhisperClientRemoveContact({
    required WhisperClient that,
    required String peer,
  });

  Future<void> crateApiWhisperWhisperClientRemoveMember({
    required WhisperClient that,
    required String groupId,
    required String peerId,
  });

  Future<void> crateApiWhisperWhisperClientRenameGroup({
    required WhisperClient that,
    required String groupId,
    required String name,
  });

  Future<void> crateApiWhisperWhisperClientSearchUsers({
    required WhisperClient that,
    required String query,
  });

  Future<void> crateApiWhisperWhisperClientSendFriendRequest({
    required WhisperClient that,
    required String target,
  });

  Future<void> crateApiWhisperWhisperClientSendGroupMessage({
    required WhisperClient that,
    required String groupId,
    required String text,
  });

  Future<void> crateApiWhisperWhisperClientSendMessage({
    required WhisperClient that,
    required String peerId,
    required String text,
  });

  Future<void> crateApiWhisperWhisperClientSendMessageFull({
    required WhisperClient that,
    required String peerId,
    required String text,
    String? quote,
    String? messageId,
    BigInt? expiresInSeconds,
  });

  Future<void> crateApiWhisperWhisperClientSendReaction({
    required WhisperClient that,
    required String peerId,
    required String messageId,
    required String emoji,
  });

  Future<void> crateApiWhisperWhisperClientSetDisplayName({
    required WhisperClient that,
    required String displayName,
  });

  Future<List<ChatEvent>> crateApiWhisperWhisperClientTakeEvents({
    required WhisperClient that,
  });

  Future<void> crateApiWhisperWhisperClientWatchPresence({
    required WhisperClient that,
    required String peerId,
  });

  Future<IdentityInfo> crateApiWhisperIdentityCreate();

  Future<IdentityInfo> crateApiWhisperIdentityFromJson({required String json});

  Future<String> crateApiWhisperInviteLink({required String json});

  Future<bool> crateApiWhisperIsValidPeerId({required String peerId});

  Future<String> crateApiWhisperSignUsername({
    required String json,
    required String username,
  });

  RustArcIncrementStrongCountFnType
  get rust_arc_increment_strong_count_WhisperClient;

  RustArcDecrementStrongCountFnType
  get rust_arc_decrement_strong_count_WhisperClient;

  CrossPlatformFinalizerArg
  get rust_arc_decrement_strong_count_WhisperClientPtr;
}

class RustLibApiImpl extends RustLibApiImplPlatform implements RustLibApi {
  RustLibApiImpl({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @override
  Future<void> crateApiWhisperWhisperClientAcceptFriendRequest({
    required WhisperClient that,
    required String peer,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerWhisperClient(
            that,
            serializer,
          );
          sse_encode_String(peer, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 1,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiWhisperWhisperClientAcceptFriendRequestConstMeta,
        argValues: [that, peer],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiWhisperWhisperClientAcceptFriendRequestConstMeta =>
      const TaskConstMeta(
        debugName: "WhisperClient_accept_friend_request",
        argNames: ["that", "peer"],
      );

  @override
  Future<void> crateApiWhisperWhisperClientAcceptGroupInvite({
    required WhisperClient that,
    required String groupId,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerWhisperClient(
            that,
            serializer,
          );
          sse_encode_String(groupId, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 2,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiWhisperWhisperClientAcceptGroupInviteConstMeta,
        argValues: [that, groupId],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiWhisperWhisperClientAcceptGroupInviteConstMeta =>
      const TaskConstMeta(
        debugName: "WhisperClient_accept_group_invite",
        argNames: ["that", "groupId"],
      );

  @override
  Future<void> crateApiWhisperWhisperClientAddGroupMember({
    required WhisperClient that,
    required String groupId,
    required String peerId,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerWhisperClient(
            that,
            serializer,
          );
          sse_encode_String(groupId, serializer);
          sse_encode_String(peerId, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 3,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiWhisperWhisperClientAddGroupMemberConstMeta,
        argValues: [that, groupId, peerId],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiWhisperWhisperClientAddGroupMemberConstMeta =>
      const TaskConstMeta(
        debugName: "WhisperClient_add_group_member",
        argNames: ["that", "groupId", "peerId"],
      );

  @override
  Future<void> crateApiWhisperWhisperClientConnect({
    required WhisperClient that,
    String? relayUrl,
    required String identityJson,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerWhisperClient(
            that,
            serializer,
          );
          sse_encode_opt_String(relayUrl, serializer);
          sse_encode_String(identityJson, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 4,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiWhisperWhisperClientConnectConstMeta,
        argValues: [that, relayUrl, identityJson],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiWhisperWhisperClientConnectConstMeta =>
      const TaskConstMeta(
        debugName: "WhisperClient_connect",
        argNames: ["that", "relayUrl", "identityJson"],
      );

  @override
  Future<void> crateApiWhisperWhisperClientCreateGroup({
    required WhisperClient that,
    required String name,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerWhisperClient(
            that,
            serializer,
          );
          sse_encode_String(name, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 5,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiWhisperWhisperClientCreateGroupConstMeta,
        argValues: [that, name],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiWhisperWhisperClientCreateGroupConstMeta =>
      const TaskConstMeta(
        debugName: "WhisperClient_create_group",
        argNames: ["that", "name"],
      );

  @override
  Future<void> crateApiWhisperWhisperClientDeclineFriendRequest({
    required WhisperClient that,
    required String peer,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerWhisperClient(
            that,
            serializer,
          );
          sse_encode_String(peer, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 6,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiWhisperWhisperClientDeclineFriendRequestConstMeta,
        argValues: [that, peer],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta
  get kCrateApiWhisperWhisperClientDeclineFriendRequestConstMeta =>
      const TaskConstMeta(
        debugName: "WhisperClient_decline_friend_request",
        argNames: ["that", "peer"],
      );

  @override
  Future<void> crateApiWhisperWhisperClientDeclineGroupInvite({
    required WhisperClient that,
    required String groupId,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerWhisperClient(
            that,
            serializer,
          );
          sse_encode_String(groupId, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 7,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiWhisperWhisperClientDeclineGroupInviteConstMeta,
        argValues: [that, groupId],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiWhisperWhisperClientDeclineGroupInviteConstMeta =>
      const TaskConstMeta(
        debugName: "WhisperClient_decline_group_invite",
        argNames: ["that", "groupId"],
      );

  @override
  Future<WhisperClient> crateApiWhisperWhisperClientDefault() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 8,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData:
              sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerWhisperClient,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiWhisperWhisperClientDefaultConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiWhisperWhisperClientDefaultConstMeta =>
      const TaskConstMeta(debugName: "WhisperClient_default", argNames: []);

  @override
  Future<void> crateApiWhisperWhisperClientDeleteMessage({
    required WhisperClient that,
    required String peerId,
    required String messageId,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerWhisperClient(
            that,
            serializer,
          );
          sse_encode_String(peerId, serializer);
          sse_encode_String(messageId, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 9,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiWhisperWhisperClientDeleteMessageConstMeta,
        argValues: [that, peerId, messageId],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiWhisperWhisperClientDeleteMessageConstMeta =>
      const TaskConstMeta(
        debugName: "WhisperClient_delete_message",
        argNames: ["that", "peerId", "messageId"],
      );

  @override
  Future<void> crateApiWhisperWhisperClientDemoteMember({
    required WhisperClient that,
    required String groupId,
    required String peerId,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerWhisperClient(
            that,
            serializer,
          );
          sse_encode_String(groupId, serializer);
          sse_encode_String(peerId, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 10,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiWhisperWhisperClientDemoteMemberConstMeta,
        argValues: [that, groupId, peerId],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiWhisperWhisperClientDemoteMemberConstMeta =>
      const TaskConstMeta(
        debugName: "WhisperClient_demote_member",
        argNames: ["that", "groupId", "peerId"],
      );

  @override
  Future<void> crateApiWhisperWhisperClientEditMessage({
    required WhisperClient that,
    required String peerId,
    required String messageId,
    required String text,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerWhisperClient(
            that,
            serializer,
          );
          sse_encode_String(peerId, serializer);
          sse_encode_String(messageId, serializer);
          sse_encode_String(text, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 11,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiWhisperWhisperClientEditMessageConstMeta,
        argValues: [that, peerId, messageId, text],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiWhisperWhisperClientEditMessageConstMeta =>
      const TaskConstMeta(
        debugName: "WhisperClient_edit_message",
        argNames: ["that", "peerId", "messageId", "text"],
      );

  @override
  Future<void> crateApiWhisperWhisperClientGetGroupInfo({
    required WhisperClient that,
    required String groupId,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerWhisperClient(
            that,
            serializer,
          );
          sse_encode_String(groupId, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 12,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiWhisperWhisperClientGetGroupInfoConstMeta,
        argValues: [that, groupId],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiWhisperWhisperClientGetGroupInfoConstMeta =>
      const TaskConstMeta(
        debugName: "WhisperClient_get_group_info",
        argNames: ["that", "groupId"],
      );

  @override
  Future<void> crateApiWhisperWhisperClientGetGroupJoinLink({
    required WhisperClient that,
    required String groupId,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerWhisperClient(
            that,
            serializer,
          );
          sse_encode_String(groupId, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 13,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiWhisperWhisperClientGetGroupJoinLinkConstMeta,
        argValues: [that, groupId],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiWhisperWhisperClientGetGroupJoinLinkConstMeta =>
      const TaskConstMeta(
        debugName: "WhisperClient_get_group_join_link",
        argNames: ["that", "groupId"],
      );

  @override
  Future<void> crateApiWhisperWhisperClientGetPresence({
    required WhisperClient that,
    required String peerId,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerWhisperClient(
            that,
            serializer,
          );
          sse_encode_String(peerId, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 14,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiWhisperWhisperClientGetPresenceConstMeta,
        argValues: [that, peerId],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiWhisperWhisperClientGetPresenceConstMeta =>
      const TaskConstMeta(
        debugName: "WhisperClient_get_presence",
        argNames: ["that", "peerId"],
      );

  @override
  Future<void> crateApiWhisperWhisperClientGetProfile({
    required WhisperClient that,
    required String peerId,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerWhisperClient(
            that,
            serializer,
          );
          sse_encode_String(peerId, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 15,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiWhisperWhisperClientGetProfileConstMeta,
        argValues: [that, peerId],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiWhisperWhisperClientGetProfileConstMeta =>
      const TaskConstMeta(
        debugName: "WhisperClient_get_profile",
        argNames: ["that", "peerId"],
      );

  @override
  Future<void> crateApiWhisperWhisperClientInviteToGroup({
    required WhisperClient that,
    required String groupId,
    required String peerId,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerWhisperClient(
            that,
            serializer,
          );
          sse_encode_String(groupId, serializer);
          sse_encode_String(peerId, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 16,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiWhisperWhisperClientInviteToGroupConstMeta,
        argValues: [that, groupId, peerId],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiWhisperWhisperClientInviteToGroupConstMeta =>
      const TaskConstMeta(
        debugName: "WhisperClient_invite_to_group",
        argNames: ["that", "groupId", "peerId"],
      );

  @override
  Future<bool> crateApiWhisperWhisperClientIsConnected({
    required WhisperClient that,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerWhisperClient(
            that,
            serializer,
          );
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 17,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_bool,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiWhisperWhisperClientIsConnectedConstMeta,
        argValues: [that],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiWhisperWhisperClientIsConnectedConstMeta =>
      const TaskConstMeta(
        debugName: "WhisperClient_is_connected",
        argNames: ["that"],
      );

  @override
  Future<void> crateApiWhisperWhisperClientJoinGroup({
    required WhisperClient that,
    required String groupId,
    required String token,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerWhisperClient(
            that,
            serializer,
          );
          sse_encode_String(groupId, serializer);
          sse_encode_String(token, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 18,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiWhisperWhisperClientJoinGroupConstMeta,
        argValues: [that, groupId, token],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiWhisperWhisperClientJoinGroupConstMeta =>
      const TaskConstMeta(
        debugName: "WhisperClient_join_group",
        argNames: ["that", "groupId", "token"],
      );

  @override
  Future<void> crateApiWhisperWhisperClientLeaveGroup({
    required WhisperClient that,
    required String groupId,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerWhisperClient(
            that,
            serializer,
          );
          sse_encode_String(groupId, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 19,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiWhisperWhisperClientLeaveGroupConstMeta,
        argValues: [that, groupId],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiWhisperWhisperClientLeaveGroupConstMeta =>
      const TaskConstMeta(
        debugName: "WhisperClient_leave_group",
        argNames: ["that", "groupId"],
      );

  @override
  Future<WhisperClient> crateApiWhisperWhisperClientNew() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 20,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData:
              sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerWhisperClient,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiWhisperWhisperClientNewConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiWhisperWhisperClientNewConstMeta =>
      const TaskConstMeta(debugName: "WhisperClient_new", argNames: []);

  @override
  Future<void> crateApiWhisperWhisperClientPromoteMember({
    required WhisperClient that,
    required String groupId,
    required String peerId,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerWhisperClient(
            that,
            serializer,
          );
          sse_encode_String(groupId, serializer);
          sse_encode_String(peerId, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 21,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiWhisperWhisperClientPromoteMemberConstMeta,
        argValues: [that, groupId, peerId],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiWhisperWhisperClientPromoteMemberConstMeta =>
      const TaskConstMeta(
        debugName: "WhisperClient_promote_member",
        argNames: ["that", "groupId", "peerId"],
      );

  @override
  Future<void> crateApiWhisperWhisperClientRefreshContacts({
    required WhisperClient that,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerWhisperClient(
            that,
            serializer,
          );
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 22,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiWhisperWhisperClientRefreshContactsConstMeta,
        argValues: [that],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiWhisperWhisperClientRefreshContactsConstMeta =>
      const TaskConstMeta(
        debugName: "WhisperClient_refresh_contacts",
        argNames: ["that"],
      );

  @override
  Future<void> crateApiWhisperWhisperClientRefreshFriendRequests({
    required WhisperClient that,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerWhisperClient(
            that,
            serializer,
          );
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 23,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiWhisperWhisperClientRefreshFriendRequestsConstMeta,
        argValues: [that],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta
  get kCrateApiWhisperWhisperClientRefreshFriendRequestsConstMeta =>
      const TaskConstMeta(
        debugName: "WhisperClient_refresh_friend_requests",
        argNames: ["that"],
      );

  @override
  Future<void> crateApiWhisperWhisperClientRefreshGroupInvites({
    required WhisperClient that,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerWhisperClient(
            that,
            serializer,
          );
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 24,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiWhisperWhisperClientRefreshGroupInvitesConstMeta,
        argValues: [that],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiWhisperWhisperClientRefreshGroupInvitesConstMeta =>
      const TaskConstMeta(
        debugName: "WhisperClient_refresh_group_invites",
        argNames: ["that"],
      );

  @override
  Future<void> crateApiWhisperWhisperClientRegisterProfile({
    required WhisperClient that,
    required String username,
    required String signature,
    String? displayName,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerWhisperClient(
            that,
            serializer,
          );
          sse_encode_String(username, serializer);
          sse_encode_String(signature, serializer);
          sse_encode_opt_String(displayName, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 25,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiWhisperWhisperClientRegisterProfileConstMeta,
        argValues: [that, username, signature, displayName],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiWhisperWhisperClientRegisterProfileConstMeta =>
      const TaskConstMeta(
        debugName: "WhisperClient_register_profile",
        argNames: ["that", "username", "signature", "displayName"],
      );

  @override
  Future<void> crateApiWhisperWhisperClientRemoveContact({
    required WhisperClient that,
    required String peer,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerWhisperClient(
            that,
            serializer,
          );
          sse_encode_String(peer, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 26,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiWhisperWhisperClientRemoveContactConstMeta,
        argValues: [that, peer],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiWhisperWhisperClientRemoveContactConstMeta =>
      const TaskConstMeta(
        debugName: "WhisperClient_remove_contact",
        argNames: ["that", "peer"],
      );

  @override
  Future<void> crateApiWhisperWhisperClientRemoveMember({
    required WhisperClient that,
    required String groupId,
    required String peerId,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerWhisperClient(
            that,
            serializer,
          );
          sse_encode_String(groupId, serializer);
          sse_encode_String(peerId, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 27,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiWhisperWhisperClientRemoveMemberConstMeta,
        argValues: [that, groupId, peerId],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiWhisperWhisperClientRemoveMemberConstMeta =>
      const TaskConstMeta(
        debugName: "WhisperClient_remove_member",
        argNames: ["that", "groupId", "peerId"],
      );

  @override
  Future<void> crateApiWhisperWhisperClientRenameGroup({
    required WhisperClient that,
    required String groupId,
    required String name,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerWhisperClient(
            that,
            serializer,
          );
          sse_encode_String(groupId, serializer);
          sse_encode_String(name, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 28,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiWhisperWhisperClientRenameGroupConstMeta,
        argValues: [that, groupId, name],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiWhisperWhisperClientRenameGroupConstMeta =>
      const TaskConstMeta(
        debugName: "WhisperClient_rename_group",
        argNames: ["that", "groupId", "name"],
      );

  @override
  Future<void> crateApiWhisperWhisperClientSearchUsers({
    required WhisperClient that,
    required String query,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerWhisperClient(
            that,
            serializer,
          );
          sse_encode_String(query, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 29,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiWhisperWhisperClientSearchUsersConstMeta,
        argValues: [that, query],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiWhisperWhisperClientSearchUsersConstMeta =>
      const TaskConstMeta(
        debugName: "WhisperClient_search_users",
        argNames: ["that", "query"],
      );

  @override
  Future<void> crateApiWhisperWhisperClientSendFriendRequest({
    required WhisperClient that,
    required String target,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerWhisperClient(
            that,
            serializer,
          );
          sse_encode_String(target, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 30,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiWhisperWhisperClientSendFriendRequestConstMeta,
        argValues: [that, target],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiWhisperWhisperClientSendFriendRequestConstMeta =>
      const TaskConstMeta(
        debugName: "WhisperClient_send_friend_request",
        argNames: ["that", "target"],
      );

  @override
  Future<void> crateApiWhisperWhisperClientSendGroupMessage({
    required WhisperClient that,
    required String groupId,
    required String text,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerWhisperClient(
            that,
            serializer,
          );
          sse_encode_String(groupId, serializer);
          sse_encode_String(text, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 31,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiWhisperWhisperClientSendGroupMessageConstMeta,
        argValues: [that, groupId, text],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiWhisperWhisperClientSendGroupMessageConstMeta =>
      const TaskConstMeta(
        debugName: "WhisperClient_send_group_message",
        argNames: ["that", "groupId", "text"],
      );

  @override
  Future<void> crateApiWhisperWhisperClientSendMessage({
    required WhisperClient that,
    required String peerId,
    required String text,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerWhisperClient(
            that,
            serializer,
          );
          sse_encode_String(peerId, serializer);
          sse_encode_String(text, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 32,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiWhisperWhisperClientSendMessageConstMeta,
        argValues: [that, peerId, text],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiWhisperWhisperClientSendMessageConstMeta =>
      const TaskConstMeta(
        debugName: "WhisperClient_send_message",
        argNames: ["that", "peerId", "text"],
      );

  @override
  Future<void> crateApiWhisperWhisperClientSendMessageFull({
    required WhisperClient that,
    required String peerId,
    required String text,
    String? quote,
    String? messageId,
    BigInt? expiresInSeconds,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerWhisperClient(
            that,
            serializer,
          );
          sse_encode_String(peerId, serializer);
          sse_encode_String(text, serializer);
          sse_encode_opt_String(quote, serializer);
          sse_encode_opt_String(messageId, serializer);
          sse_encode_opt_box_autoadd_u_64(expiresInSeconds, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 33,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiWhisperWhisperClientSendMessageFullConstMeta,
        argValues: [that, peerId, text, quote, messageId, expiresInSeconds],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiWhisperWhisperClientSendMessageFullConstMeta =>
      const TaskConstMeta(
        debugName: "WhisperClient_send_message_full",
        argNames: [
          "that",
          "peerId",
          "text",
          "quote",
          "messageId",
          "expiresInSeconds",
        ],
      );

  @override
  Future<void> crateApiWhisperWhisperClientSendReaction({
    required WhisperClient that,
    required String peerId,
    required String messageId,
    required String emoji,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerWhisperClient(
            that,
            serializer,
          );
          sse_encode_String(peerId, serializer);
          sse_encode_String(messageId, serializer);
          sse_encode_String(emoji, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 34,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiWhisperWhisperClientSendReactionConstMeta,
        argValues: [that, peerId, messageId, emoji],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiWhisperWhisperClientSendReactionConstMeta =>
      const TaskConstMeta(
        debugName: "WhisperClient_send_reaction",
        argNames: ["that", "peerId", "messageId", "emoji"],
      );

  @override
  Future<void> crateApiWhisperWhisperClientSetDisplayName({
    required WhisperClient that,
    required String displayName,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerWhisperClient(
            that,
            serializer,
          );
          sse_encode_String(displayName, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 35,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiWhisperWhisperClientSetDisplayNameConstMeta,
        argValues: [that, displayName],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiWhisperWhisperClientSetDisplayNameConstMeta =>
      const TaskConstMeta(
        debugName: "WhisperClient_set_display_name",
        argNames: ["that", "displayName"],
      );

  @override
  Future<List<ChatEvent>> crateApiWhisperWhisperClientTakeEvents({
    required WhisperClient that,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerWhisperClient(
            that,
            serializer,
          );
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 36,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_chat_event,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiWhisperWhisperClientTakeEventsConstMeta,
        argValues: [that],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiWhisperWhisperClientTakeEventsConstMeta =>
      const TaskConstMeta(
        debugName: "WhisperClient_take_events",
        argNames: ["that"],
      );

  @override
  Future<void> crateApiWhisperWhisperClientWatchPresence({
    required WhisperClient that,
    required String peerId,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerWhisperClient(
            that,
            serializer,
          );
          sse_encode_String(peerId, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 37,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiWhisperWhisperClientWatchPresenceConstMeta,
        argValues: [that, peerId],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiWhisperWhisperClientWatchPresenceConstMeta =>
      const TaskConstMeta(
        debugName: "WhisperClient_watch_presence",
        argNames: ["that", "peerId"],
      );

  @override
  Future<IdentityInfo> crateApiWhisperIdentityCreate() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 38,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_identity_info,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiWhisperIdentityCreateConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiWhisperIdentityCreateConstMeta =>
      const TaskConstMeta(debugName: "identity_create", argNames: []);

  @override
  Future<IdentityInfo> crateApiWhisperIdentityFromJson({required String json}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(json, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 39,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_identity_info,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiWhisperIdentityFromJsonConstMeta,
        argValues: [json],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiWhisperIdentityFromJsonConstMeta =>
      const TaskConstMeta(debugName: "identity_from_json", argNames: ["json"]);

  @override
  Future<String> crateApiWhisperInviteLink({required String json}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(json, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 40,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiWhisperInviteLinkConstMeta,
        argValues: [json],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiWhisperInviteLinkConstMeta =>
      const TaskConstMeta(debugName: "invite_link", argNames: ["json"]);

  @override
  Future<bool> crateApiWhisperIsValidPeerId({required String peerId}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(peerId, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 41,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_bool,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiWhisperIsValidPeerIdConstMeta,
        argValues: [peerId],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiWhisperIsValidPeerIdConstMeta =>
      const TaskConstMeta(debugName: "is_valid_peer_id", argNames: ["peerId"]);

  @override
  Future<String> crateApiWhisperSignUsername({
    required String json,
    required String username,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(json, serializer);
          sse_encode_String(username, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 42,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiWhisperSignUsernameConstMeta,
        argValues: [json, username],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiWhisperSignUsernameConstMeta =>
      const TaskConstMeta(
        debugName: "sign_username",
        argNames: ["json", "username"],
      );

  RustArcIncrementStrongCountFnType
  get rust_arc_increment_strong_count_WhisperClient => wire
      .rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerWhisperClient;

  RustArcDecrementStrongCountFnType
  get rust_arc_decrement_strong_count_WhisperClient => wire
      .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerWhisperClient;

  @protected
  WhisperClient
  dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerWhisperClient(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return WhisperClientImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  WhisperClient
  dco_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerWhisperClient(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return WhisperClientImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  WhisperClient
  dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerWhisperClient(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return WhisperClientImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  String dco_decode_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as String;
  }

  @protected
  bool dco_decode_bool(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as bool;
  }

  @protected
  BigInt dco_decode_box_autoadd_u_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_u_64(raw);
  }

  @protected
  ChatEvent dco_decode_chat_event(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 4)
      throw Exception('unexpected arr length: expect 4 but see ${arr.length}');
    return ChatEvent(
      kind: dco_decode_String(arr[0]),
      peerId: dco_decode_String(arr[1]),
      text: dco_decode_opt_String(arr[2]),
      error: dco_decode_opt_String(arr[3]),
    );
  }

  @protected
  IdentityInfo dco_decode_identity_info(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2)
      throw Exception('unexpected arr length: expect 2 but see ${arr.length}');
    return IdentityInfo(
      peerId: dco_decode_String(arr[0]),
      json: dco_decode_String(arr[1]),
    );
  }

  @protected
  List<ChatEvent> dco_decode_list_chat_event(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_chat_event).toList();
  }

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as Uint8List;
  }

  @protected
  String? dco_decode_opt_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_String(raw);
  }

  @protected
  BigInt? dco_decode_opt_box_autoadd_u_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_u_64(raw);
  }

  @protected
  BigInt dco_decode_u_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeU64(raw);
  }

  @protected
  int dco_decode_u_8(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  void dco_decode_unit(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return;
  }

  @protected
  BigInt dco_decode_usize(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeU64(raw);
  }

  @protected
  WhisperClient
  sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerWhisperClient(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return WhisperClientImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  WhisperClient
  sse_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerWhisperClient(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return WhisperClientImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  WhisperClient
  sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerWhisperClient(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return WhisperClientImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  String sse_decode_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_list_prim_u_8_strict(deserializer);
    return utf8.decoder.convert(inner);
  }

  @protected
  bool sse_decode_bool(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8() != 0;
  }

  @protected
  BigInt sse_decode_box_autoadd_u_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_u_64(deserializer));
  }

  @protected
  ChatEvent sse_decode_chat_event(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_kind = sse_decode_String(deserializer);
    var var_peerId = sse_decode_String(deserializer);
    var var_text = sse_decode_opt_String(deserializer);
    var var_error = sse_decode_opt_String(deserializer);
    return ChatEvent(
      kind: var_kind,
      peerId: var_peerId,
      text: var_text,
      error: var_error,
    );
  }

  @protected
  IdentityInfo sse_decode_identity_info(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_peerId = sse_decode_String(deserializer);
    var var_json = sse_decode_String(deserializer);
    return IdentityInfo(peerId: var_peerId, json: var_json);
  }

  @protected
  List<ChatEvent> sse_decode_list_chat_event(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <ChatEvent>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_chat_event(deserializer));
    }
    return ans_;
  }

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint8List(len_);
  }

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_String(deserializer));
    } else {
      return null;
    }
  }

  @protected
  BigInt? sse_decode_opt_box_autoadd_u_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_u_64(deserializer));
    } else {
      return null;
    }
  }

  @protected
  BigInt sse_decode_u_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getBigUint64();
  }

  @protected
  int sse_decode_u_8(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8();
  }

  @protected
  void sse_decode_unit(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  BigInt sse_decode_usize(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getBigUint64();
  }

  @protected
  int sse_decode_i_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getInt32();
  }

  @protected
  void
  sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerWhisperClient(
    WhisperClient self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as WhisperClientImpl).frbInternalSseEncode(move: true),
      serializer,
    );
  }

  @protected
  void
  sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerWhisperClient(
    WhisperClient self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as WhisperClientImpl).frbInternalSseEncode(move: false),
      serializer,
    );
  }

  @protected
  void
  sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerWhisperClient(
    WhisperClient self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as WhisperClientImpl).frbInternalSseEncode(move: null),
      serializer,
    );
  }

  @protected
  void sse_encode_String(String self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_prim_u_8_strict(utf8.encoder.convert(self), serializer);
  }

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self ? 1 : 0);
  }

  @protected
  void sse_encode_box_autoadd_u_64(BigInt self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_u_64(self, serializer);
  }

  @protected
  void sse_encode_chat_event(ChatEvent self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.kind, serializer);
    sse_encode_String(self.peerId, serializer);
    sse_encode_opt_String(self.text, serializer);
    sse_encode_opt_String(self.error, serializer);
  }

  @protected
  void sse_encode_identity_info(IdentityInfo self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.peerId, serializer);
    sse_encode_String(self.json, serializer);
  }

  @protected
  void sse_encode_list_chat_event(
    List<ChatEvent> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_chat_event(item, serializer);
    }
  }

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint8List(self);
  }

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_String(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_u_64(BigInt? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_u_64(self, serializer);
    }
  }

  @protected
  void sse_encode_u_64(BigInt self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putBigUint64(self);
  }

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self);
  }

  @protected
  void sse_encode_unit(void self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  void sse_encode_usize(BigInt self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putBigUint64(self);
  }

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putInt32(self);
  }
}

@sealed
class WhisperClientImpl extends RustOpaque implements WhisperClient {
  // Not to be used by end users
  WhisperClientImpl.frbInternalDcoDecode(List<dynamic> wire)
    : super.frbInternalDcoDecode(wire, _kStaticData);

  // Not to be used by end users
  WhisperClientImpl.frbInternalSseDecode(BigInt ptr, int externalSizeOnNative)
    : super.frbInternalSseDecode(ptr, externalSizeOnNative, _kStaticData);

  static final _kStaticData = RustArcStaticData(
    rustArcIncrementStrongCount:
        RustLib.instance.api.rust_arc_increment_strong_count_WhisperClient,
    rustArcDecrementStrongCount:
        RustLib.instance.api.rust_arc_decrement_strong_count_WhisperClient,
    rustArcDecrementStrongCountPtr:
        RustLib.instance.api.rust_arc_decrement_strong_count_WhisperClientPtr,
  );

  Future<void> acceptFriendRequest({required String peer}) => RustLib
      .instance
      .api
      .crateApiWhisperWhisperClientAcceptFriendRequest(that: this, peer: peer);

  Future<void> acceptGroupInvite({required String groupId}) =>
      RustLib.instance.api.crateApiWhisperWhisperClientAcceptGroupInvite(
        that: this,
        groupId: groupId,
      );

  Future<void> addGroupMember({
    required String groupId,
    required String peerId,
  }) => RustLib.instance.api.crateApiWhisperWhisperClientAddGroupMember(
    that: this,
    groupId: groupId,
    peerId: peerId,
  );

  Future<void> connect({String? relayUrl, required String identityJson}) =>
      RustLib.instance.api.crateApiWhisperWhisperClientConnect(
        that: this,
        relayUrl: relayUrl,
        identityJson: identityJson,
      );

  Future<void> createGroup({required String name}) => RustLib.instance.api
      .crateApiWhisperWhisperClientCreateGroup(that: this, name: name);

  Future<void> declineFriendRequest({required String peer}) => RustLib
      .instance
      .api
      .crateApiWhisperWhisperClientDeclineFriendRequest(that: this, peer: peer);

  Future<void> declineGroupInvite({required String groupId}) =>
      RustLib.instance.api.crateApiWhisperWhisperClientDeclineGroupInvite(
        that: this,
        groupId: groupId,
      );

  /// Delete a message for everyone.
  Future<void> deleteMessage({
    required String peerId,
    required String messageId,
  }) => RustLib.instance.api.crateApiWhisperWhisperClientDeleteMessage(
    that: this,
    peerId: peerId,
    messageId: messageId,
  );

  Future<void> demoteMember({
    required String groupId,
    required String peerId,
  }) => RustLib.instance.api.crateApiWhisperWhisperClientDemoteMember(
    that: this,
    groupId: groupId,
    peerId: peerId,
  );

  /// Edit a message's text.
  Future<void> editMessage({
    required String peerId,
    required String messageId,
    required String text,
  }) => RustLib.instance.api.crateApiWhisperWhisperClientEditMessage(
    that: this,
    peerId: peerId,
    messageId: messageId,
    text: text,
  );

  Future<void> getGroupInfo({required String groupId}) => RustLib.instance.api
      .crateApiWhisperWhisperClientGetGroupInfo(that: this, groupId: groupId);

  Future<void> getGroupJoinLink({required String groupId}) =>
      RustLib.instance.api.crateApiWhisperWhisperClientGetGroupJoinLink(
        that: this,
        groupId: groupId,
      );

  Future<void> getPresence({required String peerId}) => RustLib.instance.api
      .crateApiWhisperWhisperClientGetPresence(that: this, peerId: peerId);

  /// Fetch a peer's public profile.
  Future<void> getProfile({required String peerId}) => RustLib.instance.api
      .crateApiWhisperWhisperClientGetProfile(that: this, peerId: peerId);

  Future<void> inviteToGroup({
    required String groupId,
    required String peerId,
  }) => RustLib.instance.api.crateApiWhisperWhisperClientInviteToGroup(
    that: this,
    groupId: groupId,
    peerId: peerId,
  );

  Future<bool> isConnected() =>
      RustLib.instance.api.crateApiWhisperWhisperClientIsConnected(that: this);

  Future<void> joinGroup({required String groupId, required String token}) =>
      RustLib.instance.api.crateApiWhisperWhisperClientJoinGroup(
        that: this,
        groupId: groupId,
        token: token,
      );

  Future<void> leaveGroup({required String groupId}) => RustLib.instance.api
      .crateApiWhisperWhisperClientLeaveGroup(that: this, groupId: groupId);

  Future<void> promoteMember({
    required String groupId,
    required String peerId,
  }) => RustLib.instance.api.crateApiWhisperWhisperClientPromoteMember(
    that: this,
    groupId: groupId,
    peerId: peerId,
  );

  Future<void> refreshContacts() => RustLib.instance.api
      .crateApiWhisperWhisperClientRefreshContacts(that: this);

  Future<void> refreshFriendRequests() => RustLib.instance.api
      .crateApiWhisperWhisperClientRefreshFriendRequests(that: this);

  Future<void> refreshGroupInvites() => RustLib.instance.api
      .crateApiWhisperWhisperClientRefreshGroupInvites(that: this);

  /// Register (or refresh) a signed username + optional display name.
  Future<void> registerProfile({
    required String username,
    required String signature,
    String? displayName,
  }) => RustLib.instance.api.crateApiWhisperWhisperClientRegisterProfile(
    that: this,
    username: username,
    signature: signature,
    displayName: displayName,
  );

  Future<void> removeContact({required String peer}) => RustLib.instance.api
      .crateApiWhisperWhisperClientRemoveContact(that: this, peer: peer);

  Future<void> removeMember({
    required String groupId,
    required String peerId,
  }) => RustLib.instance.api.crateApiWhisperWhisperClientRemoveMember(
    that: this,
    groupId: groupId,
    peerId: peerId,
  );

  Future<void> renameGroup({required String groupId, required String name}) =>
      RustLib.instance.api.crateApiWhisperWhisperClientRenameGroup(
        that: this,
        groupId: groupId,
        name: name,
      );

  /// Search the public directory by username / peer ID.
  Future<void> searchUsers({required String query}) => RustLib.instance.api
      .crateApiWhisperWhisperClientSearchUsers(that: this, query: query);

  Future<void> sendFriendRequest({required String target}) =>
      RustLib.instance.api.crateApiWhisperWhisperClientSendFriendRequest(
        that: this,
        target: target,
      );

  /// Send a text message to a group (Megolm-encrypted). The session key is
  /// shared to members over 1:1 E2EE; for the MVP we reuse the same
  /// envelope routing with a group recipient and an encrypted payload.
  Future<void> sendGroupMessage({
    required String groupId,
    required String text,
  }) => RustLib.instance.api.crateApiWhisperWhisperClientSendGroupMessage(
    that: this,
    groupId: groupId,
    text: text,
  );

  Future<void> sendMessage({required String peerId, required String text}) =>
      RustLib.instance.api.crateApiWhisperWhisperClientSendMessage(
        that: this,
        peerId: peerId,
        text: text,
      );

  Future<void> sendMessageFull({
    required String peerId,
    required String text,
    String? quote,
    String? messageId,
    BigInt? expiresInSeconds,
  }) => RustLib.instance.api.crateApiWhisperWhisperClientSendMessageFull(
    that: this,
    peerId: peerId,
    text: text,
    quote: quote,
    messageId: messageId,
    expiresInSeconds: expiresInSeconds,
  );

  /// Send an emoji reaction to a message (encrypted inside the session).
  Future<void> sendReaction({
    required String peerId,
    required String messageId,
    required String emoji,
  }) => RustLib.instance.api.crateApiWhisperWhisperClientSendReaction(
    that: this,
    peerId: peerId,
    messageId: messageId,
    emoji: emoji,
  );

  /// Set our public display name.
  Future<void> setDisplayName({required String displayName}) =>
      RustLib.instance.api.crateApiWhisperWhisperClientSetDisplayName(
        that: this,
        displayName: displayName,
      );

  Future<List<ChatEvent>> takeEvents() =>
      RustLib.instance.api.crateApiWhisperWhisperClientTakeEvents(that: this);

  Future<void> watchPresence({required String peerId}) => RustLib.instance.api
      .crateApiWhisperWhisperClientWatchPresence(that: this, peerId: peerId);
}
